# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'ConverterDemo' do
  # Uncomment the next line if you're using Swift or would like to use dynamic frameworks
  # use_frameworks!

  # Pods for ConverterDemo

  pod 'AFNetworking', '~> 3.0'
  pod 'Realm'
  pod 'MBProgressHUD', '~> 1.0.0'


end
